config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: { sessions: 'admin/sessions' }
  devise_for :users

  root 'homes#top'
  get 'about' => 'homes#about'
  get 'inquiries/complete' => 'inquiries#complete'

  resources :graves, only: [:index, :show]  # 墓所管理
  resources :inquiries, only: [:new, :create]
  resources :users, only: [:show]

  # マイページ関連
  get 'mypage' => 'users#mypage'
  get 'mypage/edit' => 'users#edit', as: 'edit_mypage'
  patch 'mypage' => 'users#update'

  resources :posts do
    collection { get :liked }
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :graves do
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:new, :create]
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy], shallow: true
  end

  # 検索
  resource :search, only: [:new, :show], controller: 'searches'
  resource :user_search, only: [:show], controller: 'user_searches'

  resources :users do
    member { get :following, :followers }
  end
  resources :relationships, only: [:create, :destroy]

  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'dashboards', to: 'dashboards#index'

    resources :graves
    resources :users, only: [:index, :show, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :reports, only: [:index, :show, :update]
    resources :genres, except: [:new, :show]
    resources :comments, only: [:index, :destroy]
    resources :inquiries, only: [:index, :show, :update]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  def index
    # 関連するユーザーと投稿の情報を一度に取得してN+1問題を解消
    @comments = Comment.all.includes(:user, :post).order(created_at: :desc)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path, notice: 'コメントを削除しました。'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.build(comment_params)
      @comment.user_id = current_user.id
      
      if @comment.save
        redirect_to post_path(@post), notice: 'コメントを投稿しました。'
      else
        # 失敗した場合、投稿詳細ページの情報を再度取得して表示
        @comments = @post.comments.includes(:user)
        flash.now[:alert] = 'コメントを入力してください'
        render 'posts/show'
      end
    end
  
    def destroy
      @comment = Comment.find(params[:id])
      # 自分のコメントでなければ削除させない
      if @comment.user == current_user
        @comment.destroy
        redirect_to post_path(@comment.post), notice: 'コメントを削除しました。'
      else
        redirect_to post_path(@comment.post), alert: '他人のコメントは削除できません。'
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:body)
    end
  end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/comments/index.html.erb
<div class="container">
  <h3 class="my-4">コメント一覧</h3>
  
  <table class="table table-hover">
    <thead class="thead-light">
      <tr>
        <th>ID</th>
        <th style="width: 40%;">コメント内容</th>
        <th>コメント投稿者</th>
        <th>関連する投稿</th>
        <th>投稿日時</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.id %></td>
          <td><%= comment.body %></td>
          <td><%= comment.user.name %></td>
          <%# 投稿が存在する場合のみリンクを表示 %>
          <td><%= link_to comment.post.title, admin_post_path(comment.post) if comment.post %></td>
          <td><%= l comment.created_at, format: :short %></td>
          <td>
            <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>