config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: { sessions: 'admin/sessions' }
  devise_for :users

  root 'homes#top'
  get 'about' => 'homes#about'
  get 'inquiries/complete' => 'inquiries#complete'

  resources :graves, only: [:index, :show]  # 墓所管理
  resources :inquiries, only: [:new, :create]
  resources :users, only: [:show]

  # マイページ関連
  get 'mypage' => 'users#mypage'
  get 'mypage/edit' => 'users#edit', as: 'edit_mypage'
  patch 'mypage' => 'users#update'

  resources :posts do
    collection { get :liked }
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :graves do
    resources :comments, only: [:create, :destroy]
    resources :reports, only: [:new, :create]
    resources :posts, only: [:new, :create, :show, :edit, :update, :destroy], shallow: true
  end

  # 検索
  resource :search, only: [:new, :show], controller: 'searches'
  resource :user_search, only: [:show], controller: 'user_searches'

  resources :users do
    member { get :following, :followers }
  end
  resources :relationships, only: [:create, :destroy]

  # ゲストユーザー
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # 管理者用
  namespace :admin do
    root to: 'homes#top'
    get 'dashboards', to: 'dashboards#index'

    resources :graves
    resources :users, only: [:index, :show, :update, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :reports, only: [:index, :show, :update]
    resources :genres, except: [:new, :show]
    resources :comments, only: [:index, :destroy]
    resources :inquiries, only: [:index, :show, :update]
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
    layout 'admin' # ここを追加
    before_action :authenticate_admin!
    def index
        @users = User.all
    end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<div class="container my-5">
  <div class="card shadow-sm">
    <div class="card-header bg-primary text-white">
      <h2 class="mb-0">管理者ページ</h2>
    </div>
    <div class="card-body">
      <div class="list-group">
        <%= link_to "会員一覧", admin_users_path, class: "list-group-item list-group-item-action" %>
        <%= link_to "投稿一覧", admin_posts_path, class: "list-group-item list-group-item-action" %>
        <%= link_to "コメント一覧", admin_comments_path, class: "list-group-item list-group-item-action" %>
        <%= link_to "墓所一覧", admin_graves_path, class: "list-group-item list-group-item-action" %>
        <%= link_to "ジャンル一覧・追加", admin_genres_path, class: "list-group-item list-group-item-action" %>
        <%= link_to "通報一覧", admin_inquiries_path, class: "list-group-item list-group-item-action" %>
      </div>
    </div>
  </div>
</div>